# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    command: sh -c "sleep 3; flask run --host=0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:password@db:5432/surveydb
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=False
      - MAIL_USE_SSL=False
      - MAIL_DEFAULT_SENDER=noreply@survey.com
    depends_on:
      - redis
      - db
      - mailhog

  worker:
    build: .
    command: sh -c "sleep 3; flask run --host=0.0.0.0"
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:password@db:5432/surveydb
      - MAIL_SERVER=mailhog
      - MAIL_PORT=1025
      - MAIL_USE_TLS=False
      - MAIL_USE_SSL=False
    depends_on:
      - redis
      - db
      - mailhog

  redis:
    image: "redis:7.2.5"
    ports:
      - "6379:6379"

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: surveydb
    ports:
      - "5432:5432"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"  # SMTP server
      - "8025:8025"  # Web UI